google/dart-neats

sanitize_html/CHANGELOG.md
sanitize_html/lib/src/html_formatter.dart
sanitize_html/pubspec.yaml
sanitize_html/test/sanitize_html_test.dart

Fix issue #11, only use self-closing tags for void-elements

---

shelf_router_generator/CHANGELOG.md
shelf_router_generator/example/main.g.dart
shelf_router_generator/lib/src/shelf_router_generator.dart
shelf_router_generator/pubspec.yaml
shelf_router_generator/test/server/api.dart
shelf_router_generator/test/server/api.g.dart
shelf_router_generator/test/server/service.g.dart

Using raw string literals in generated code.
This aims to fix issue #10.
Note. the commits can be review independently.

Fix issue #10

---

neat_periodic_task/CHANGELOG.md
neat_periodic_task/lib/src/neat_status.g.dart
neat_periodic_task/pubspec.yaml

Just another dependency update.

Relax json_annotation dependency constraint

---

retry/README.md

Fixing maxAttempts in readme.md

---

retry/CHANGELOG.md
retry/pubspec.yaml

Credits to @karl3i for updating the `README.md` in https://github.com/google/dart-neats/pull/23.

Release retry 3.0.0+1

---

.github/ISSUE_TEMPLATE/safe_url_check.md
safe_url_check/CHANGELOG.md
safe_url_check/LICENSE
safe_url_check/README.md
safe_url_check/analysis_options.yaml
safe_url_check/example/main.dart
safe_url_check/lib/safe_url_check.dart
safe_url_check/lib/src/private_ip.dart
safe_url_check/lib/src/unique_local_ip.dart
safe_url_check/lib/src/version.dart
safe_url_check/mono_pkg.yaml
safe_url_check/pubspec.yaml
safe_url_check/test/private_ip_test.dart
safe_url_check/test/safe_url_check_test.dart
safe_url_check/test/unique_local_ip_test.dart

Thinking we could use this to fix https://github.com/dart-lang/pana/issues/554
Note, I doubt requests to private IPs could actually cause any security vulnerabilities, but it is always nice to prevent these sorts of things.

Initial release of package:safe_url_check

---

chunked_stream/CHANGELOG.md
chunked_stream/lib/chunked_stream.dart
chunked_stream/lib/src/chunk_stream.dart
chunked_stream/lib/src/chunked_stream_iterator.dart
chunked_stream/lib/src/read_chunked_stream.dart
chunked_stream/pubspec.yaml
chunked_stream/test/chunk_stream_test.dart
chunked_stream/test/chunked_stream_buffer_test.dart

Added asChunkedStream to package:chunked_stream

---

yaml_edit/test/naughty_test.dart
yaml_edit/test/random_test.dart

Using runZoned to remove test pollution

---

.travis.yml
acyclic_steps/mono_pkg.yaml
canonical_json/mono_pkg.yaml
chunked_stream/mono_pkg.yaml
http_methods/mono_pkg.yaml
mono_repo.yaml
neat_cache/mono_pkg.yaml
neat_periodic_task/mono_pkg.yaml
neat_periodic_task/test/ensure_build_test.dart
pem/mono_pkg.yaml
retry/mono_pkg.yaml
safe_url_check/mono_pkg.yaml
sanitize_html/mono_pkg.yaml
shelf_router/mono_pkg.yaml
shelf_router_generator/mono_pkg.yaml
shelf_router_generator/test/ensure_build_test.dart
slugid/mono_pkg.yaml
tool/travis.sh
yaml_edit/mono_pkg.yaml

- Added `acyclic_json`, `safe_url_check` and `yaml_edit` to travis jobs 
- Also commented out two `ensure_build_test` that were likely failing due to a `build_runner` issue

Updated Travis configuration to allow packages to be tested in parallel jobs

---

yaml_edit/pubspec.yaml

Remove yaml_edit dependency on quiver_hashcode

---

sanitize_html/CHANGELOG.md
sanitize_html/lib/src/sane_html_validator.dart
sanitize_html/pubspec.yaml
sanitize_html/test/sanitize_html_test.dart

(The title is fairly self-explanatory, but there's more detail in #71)
Fixes https://github.com/google/dart-neats/issues/71

[sanitize_html] Don't call addLinkRel if it's null

---

yaml_edit/lib/src/editor.dart

Minor typo fixes + line width adhering + documentation reference fixes.

Minor documentation fixes for yaml_edit

---

yaml_edit/lib/src/strings.dart
yaml_edit/test/update_test.dart
yaml_edit/test/wrap_test.dart

Resolves #77.
If this PR is accepted, I'm planning on improving the testing and make it a patch release!
/cc @jonasfj

Fixed bug with adding empty map

---

.github/workflows/dart.yml
sanitize_html/CHANGELOG.md
sanitize_html/lib/sanitize_html.dart
sanitize_html/lib/src/html_formatter.dart
sanitize_html/lib/src/sane_html_validator.dart
sanitize_html/mono_pkg.yaml
sanitize_html/pubspec.yaml
sanitize_html/test/sanitize_html_test.dart

Merging master and fixing CI for https://github.com/google/dart-neats/pull/103

Merged master into #103

---

.github/workflows/dart.yml
http_methods/CHANGELOG.md
http_methods/mono_pkg.yaml
http_methods/pubspec.yaml
shelf_router/CHANGELOG.md
shelf_router/lib/src/router.dart
shelf_router/lib/src/router_entry.dart
shelf_router/mono_pkg.yaml
shelf_router/pubspec.yaml
shelf_router/test/route_entry_test.dart
shelf_router/test/router_test.dart

Migrate shelf_router to Dart null safety

---

yaml_edit/lib/src/editor.dart
yaml_edit/lib/src/equality.dart
yaml_edit/lib/src/errors.dart
yaml_edit/lib/src/list_mutations.dart
yaml_edit/lib/src/map_mutations.dart
yaml_edit/lib/src/source_edit.dart
yaml_edit/lib/src/strings.dart
yaml_edit/lib/src/utils.dart
yaml_edit/lib/src/wrap.dart
yaml_edit/pubspec.yaml
yaml_edit/test/append_test.dart
yaml_edit/test/golden_test.dart
yaml_edit/test/naughty_test.dart
yaml_edit/test/parse_test.dart
yaml_edit/test/prepend_test.dart
yaml_edit/test/random_test.dart
yaml_edit/test/remove_test.dart
yaml_edit/test/test_case.dart
yaml_edit/test/test_utils.dart
yaml_edit/test/update_test.dart

Hi,
For this part, I tried to focus the changes on the tests first by fixing the null safety errors I found when running `dart analyze`. There were analyze errors on the lib directory but I tried to fix only the parts where the interfaces don't match the tests and a few low-hanging fruits.
I figured this will be a good place start to discuss what needs to change.
Tagging @jonasfj

yaml_edit nullsafety

---

chunked_stream/CHANGELOG.md
chunked_stream/lib/src/chunked_stream_iterator.dart
chunked_stream/pubspec.yaml

Fixes https://github.com/google/dart-neats/issues/117

Deprecating ChunkedStreamReader

---

shelf_router/README.md

Fix Syntax Error in Readme

---

yaml_edit/lib/src/editor.dart
yaml_edit/lib/src/map_mutations.dart

@jonasfj Here are the edits from the nits. :)

yaml_edit null safety minor refactorings

---

shelf_router/lib/shelf_router.dart
shelf_router/lib/src/router.dart

Fixed syntax error in documentation.

---

neat_cache/CHANGELOG.md
neat_cache/example/main.dart
neat_cache/lib/cache_provider.dart
neat_cache/lib/neat_cache.dart
neat_cache/lib/src/providers/inmemory.dart
neat_cache/lib/src/providers/redis.dart
neat_cache/lib/src/providers/resp.dart
neat_cache/pubspec.yaml
neat_cache/test/cache_test.dart
neat_cache/test/cachefailure_test.dart
neat_cache/test/cacheprovider_test.dart
neat_cache/test/redis_test.dart
neat_cache/test/resp_test.dart
neat_cache/test/utils.dart

Null-safety migration of neat_cache

---

sanitize_html/README.md

Properly capitalize JavaScript and GitHub.

Update README with correct capitalization

---

shelf_router/CHANGELOG.md
shelf_router/lib/src/router.dart
shelf_router/pubspec.yaml
shelf_router/test/router_test.dart

- closes #67 (related to #140)

fix: mount remove trailing slash requirement

---

canonical_json/CHANGELOG.md
canonical_json/README.md
canonical_json/pubspec.yaml

Just aiming to score some more delicious points: https://pub.dev/packages/canonical_json/score

Prepare 1.1.1

---

.github/dependabot.yml
.github/workflows/publish.yml

blast_repo fixes

---

acyclic_steps/CHANGELOG.md
acyclic_steps/pubspec.yaml
canonical_json/CHANGELOG.md
canonical_json/pubspec.yaml
chunked_stream/CHANGELOG.md
chunked_stream/pubspec.yaml
http_methods/CHANGELOG.md
http_methods/pubspec.yaml
neat_cache/CHANGELOG.md
neat_cache/pubspec.yaml
neat_periodic_task/CHANGELOG.md
neat_periodic_task/pubspec.yaml
pem/CHANGELOG.md
pem/pubspec.yaml
safe_url_check/CHANGELOG.md
safe_url_check/pubspec.yaml
sanitize_html/CHANGELOG.md
sanitize_html/pubspec.yaml
slugid/CHANGELOG.md
slugid/pubspec.yaml
vendor/CHANGELOG.md
vendor/pubspec.yaml

Add `topics` to `pubspec.yaml`

---

vendor/CHANGELOG.md
vendor/pubspec.yaml

Follow up on https://github.com/google/dart-neats/pull/260

Publish package:vendor 0.9.7

---

typed_sql/CHANGELOG.md
typed_sql/doc/05_foreign_keys.md
typed_sql/example/lib/src/model.g.dart
typed_sql/lib/builder.dart
typed_sql/lib/src/codegen/build_code.dart
typed_sql/lib/src/codegen/parse_library.dart
typed_sql/lib/src/codegen/parsed_library.dart
typed_sql/lib/src/codegen/type_checkers.dart
typed_sql/lib/src/typed_sql.annotations.dart
typed_sql/test/sqlite/model.g.dart
typed_sql/test/typed_sql/documentation/model_documentation_test.g.dart
typed_sql/test/typed_sql/example/blog/blog_test.dart
typed_sql/test/typed_sql/example/blog/blog_test.g.dart
typed_sql/test/typed_sql/example/bookstore/bookstore_test.g.dart
typed_sql/test/typed_sql/example/schema/schema_test.g.dart
typed_sql/test/typed_sql/foreign_key/composite_foreign_key/composite_foreign_key_test.dart
typed_sql/test/typed_sql/foreign_key/composite_foreign_key/composite_foreign_key_test.g.dart
typed_sql/test/typed_sql/foreign_key/nullable_composite_foreign_key/nullable_composite_foreign_key_test.dart
typed_sql/test/typed_sql/foreign_key/nullable_composite_foreign_key/nullable_composite_foreign_key_test.g.dart
typed_sql/test/typed_sql/foreign_key/simple_foreign_key/simple_foreign_key_test.dart
typed_sql/test/typed_sql/foreign_key/simple_foreign_key/simple_foreign_key_test.g.dart
typed_sql/test/typed_sql/group_by/group_by_reference/group_by_reference_test.g.dart
typed_sql/test/typed_sql/references/nullable_reference/nullable_reference_test.g.dart
typed_sql/test/typed_sql/references/references_id_as/references_id_as_test.g.dart

* First commit is the one with changes to code gen
* Second commit change how we parse annotations
* The rest is documentation and tests, feel free to ignore/skim it

Composite foreign keys
