- sanitize_html/CHANGELOG.md
- sanitize_html/lib/sanitize_html.dart
- sanitize_html/lib/src/html_formatter.dart
- sanitize_html/lib/src/sane_html_validator.dart
- sanitize_html/pubspec.yaml
- sanitize_html/test/sanitize_html_test.dart
- fixes #2 
- no longer depends on `universal_html`:
- custom output formatting that keeps no-content tags as self-closing: `<img />`
I've wanted to create a separate library for the formatting (e.g. allow indents and a canonical formatting of the html markup), but the edges cases are hard to deal with, and I've settled with this simple solution.
The runZoned part could be probably removed? /cc @jonasfj
> Improved sanitization and formatting.

- neat_cache/CHANGELOG.md
- neat_cache/lib/neat_cache.dart
- neat_cache/pubspec.yaml
I don't think there is any reasonable cases where you
will want to purge the cache from an _up-sert_ creator
callback.
Probably the `create` function returns `null` because
there is no value to be stored, and thus, nothing
should be cached.
Note. In generate `set(null)` will still call `purge()`.
Thus, `null` cannot be used to cache no-value.
> Avoid unnecessary purge when .get(() => null) is called

- shelf_router_generator/test/server/service.dart
- shelf_router_generator/test/server/unrelatedannotation.dart
Simple test that we don't generate code on unrelated annotations.
> Test that unrelated annotations does not affect code-gen

- acyclic_steps/CHANGELOG.md
- acyclic_steps/lib/src/fluent_api.dart
- acyclic_steps/pubspec.yaml
The issues is specific to generic type functions, and the workaround
seems very cheap with no impact on behavior.
> Workaround `ArgumentError.checkNotNull` regression in Dart 2.8.1

- retry/CHANGELOG.md
- retry/lib/retry.dart
- retry/pubspec.yaml
- retry/test/retry_test.dart
When I use retry with relatively big number of attempt (like 64), delay is overflow. It is because delay is calculated by int.
I change it to floating point so that it won't overflow. I added test also.
> fix retry overflow

- shelf_router/CHANGELOG.md
- shelf_router/example/main.dart
- shelf_router/lib/src/router.dart
- shelf_router/pubspec.yaml
- shelf_router/test/router_test.dart
`Router.mount()` can take a `Handler` so we can have middlewares for sub routes.
And make Router to be a Handler to preserve backward compatibility.
> Router: allow to mount a Handler

- chunked_stream/CHANGELOG.md
- chunked_stream/example/main.dart
- chunked_stream/lib/src/chunked_stream_iterator.dart
- chunked_stream/lib/src/read_chunked_stream.dart
- chunked_stream/pubspec.yaml
- chunked_stream/test/chunked_stream_iterator_test.dart
Updated the implementation of `ChunkedStreamIterator` to fix bugs raised in previous issues. As far as I can tell, the public API still stays the same, so it shouldn't be a breaking change I think?
Closes #66 
Closes #62 
/cc @jonasfj
> Chunked Stream Iterator update

- chunked_stream/CHANGELOG.md
- chunked_stream/README.md
- chunked_stream/lib/chunked_stream.dart
- chunked_stream/lib/src/chunked_stream_iterator.dart
- chunked_stream/lib/src/read_chunked_stream.dart
- chunked_stream/pubspec.yaml
- chunked_stream/test/chunked_stream_iterator_test.dart
- chunked_stream/test/read_chunked_stream_test.dart
@simolus3
Given that we use `.sublist` in `ChunkedStreamIterator` we don't really need to do much to byte stream specially.
Well, at-least not if those byte streams contains `Uint8List` which many of the streams from `dart:io` do, even if the type is `Stream<List<int>>`. Besides, even if there is a `List<int>` instance in there, most of the chunks are probably not going to be split, as they just pass right through.
The only place where it's a bit annoying is `ChunkedStreamIterator.read`, but I figured we could just introduce an extension method `ChunkedStreamIterator.readBytes` which returns `Uint8List`. I doubt there are many special cases where you want to use a specific kind of List type, it pretty much only makes sense for byte streams (I hope).
Also added `readByteStream` to …
> Added readByteStream and prepare 1.4.0-null-safe.0 release

- .github/workflows/dart.yml
- chunked_stream/CHANGELOG.md
- chunked_stream/lib/src/chunk_stream.dart
- chunked_stream/lib/src/chunked_stream_buffer.dart
- chunked_stream/lib/src/read_chunked_stream.dart
- chunked_stream/pubspec.yaml
- retry/mono_pkg.yaml
- Remove `-nullsafety` suffix from version
- Remove `ArgumentError.checkNotNull` for non-nullable arguments
- Set min SDK to current beta based on the [guidelines](https://dart.dev/null-safety/migration-guide#sdk-constraints)
- Use stable versions of dependencies
> Prepare stable chunked_stream release

- yaml_edit/test/parse_test.dart
This is just additional coverage for parsing YAML documents with null values.
@jonasfj
> [yaml_edit] Testcases for `parseAt()` with null values

- shelf_router_generator/CHANGELOG.md
- shelf_router_generator/example/main.dart
- shelf_router_generator/example/main.g.dart
- shelf_router_generator/lib/src/shelf_router_generator.dart
- shelf_router_generator/pubspec.yaml
- shelf_router_generator/test/server/api.dart
- shelf_router_generator/test/server/api.g.dart
- shelf_router_generator/test/server/server.dart
- shelf_router_generator/test/server/service.dart
- shelf_router_generator/test/server/service.g.dart
- shelf_router_generator/test/server/unrelatedannotation.dart
- shelf_router_generator/test/server_test.dart
Just need to wait on pkg:source_gen to get published to make this fully null-safe
> shelf_router_generator: Support null-safe dependencies

- shelf_router/CHANGELOG.md
- shelf_router/lib/src/router.dart
- shelf_router/pubspec.yaml
- shelf_router/test/router_test.dart
Fixing https://github.com/google/dart-neats/issues/136
> Introduce `routeNotFound` sentinel for shelf_router 1.1.0

- shelf_router/CHANGELOG.md
- shelf_router/lib/src/router.dart
- shelf_router/pubspec.yaml
- shelf_router/test/router_test.dart
- Fixes #144, a slightly more compact version of #145.
- Additional test.
> Fix Router.routeNotFound to enable multiple read() calls on it.

- http_methods/pubspec.yaml
- neat_periodic_task/pubspec.yaml
- pem/pubspec.yaml
- retry/pubspec.yaml
- sanitize_html/pubspec.yaml
- shelf_router/pubspec.yaml
- slugid/pubspec.yaml
Just to reduce warnings when publishing in the future.
> Fix SDK constraints 2.12.0-0 to 2.12.0

- api_analysis/lib/r2/analyze.dart
I think this is probably closer to the intended logic:
- if `definedShapes` _contains_ a key with the name of this symbol, then we should _continue_ to the next symbol
- this is an `extension on PackageShape` so `name` refers to the name of this `PackageShape`. we probably want to use `d.nameAsString` instead.
- for me, shadowing makes the code a little less clear to read. in this case, it prevents us from checking what other accessors share the name of the symbol `d` in line 239
> api_analysis_exploration: improve summary logic for getters/setters

- api_analysis/example/lib/foo.dart
- api_analysis/lib/r2/analyze.dart
also add example demonstrating the fix
named parameters always have a name (**I hope I got this right!**)
> api_analysis_exploration: account for the case that the `Token` associated with a named parameter is a `StringToken`

- api_analysis/lib/common.dart
- api_analysis/lib/fast/analyze.dart
We might also want to clean up r1 and r2 in this way.
> api_analysis_exploration: move common functionality into `common.dart`

- api_analysis/lib/common.dart
- api_analysis/lib/fast/analyze.dart
- api_analysis/lib/r3/analyze.dart
- api_analysis/lib/r3/outline.dart
- api_analysis/lib/r3/shapes.dart
- api_analysis/lib/r3/shapes.g.dart
- api_analysis/pubspec.yaml
This includes propagation of exports, so the summary produced should be fairly comprehensive.
One can analyse a local package to obtain a full summary, or a hosted package, in which case all appropriate versions are analysed and the differences displayed.
It remains to add a README description.
> api_analysis_exploration: add r3 experiment

- safe_url_check/CHANGELOG.md
- safe_url_check/lib/safe_url_check.dart
- safe_url_check/lib/src/safe_url_check.dart
- safe_url_check/lib/src/version.dart
- safe_url_check/pubspec.yaml
- safe_url_check/test/relative_redirect_test.dart
- safe_url_check/test/safe_url_check_test.dart
> Allow relative URLs in the redirect location header.

- neat_periodic_task/lib/neat_periodic_task.dart
Documentation update to fix https://github.com/google/dart-neats/issues/210
Context: `NeatPeriodicTaskScheduler` is intended to be used for background task that run for the duration of the process. This is generally aimed at the server space where the task state is persistent in a database or similar thing.
> Updated documentation comments

- pem/pubspec.yaml
This PR changes `pem` package:
- updates version of dependency `petitparser` from 5.1.0 to 6.0.2;
- updates version of dev dependency `lints` from 1.0.0 to 3.0.0;
> pem: Bump petitparser from 5.1.0 to 6.0.2

- neat_cache/CHANGELOG.md
- neat_cache/lib/src/providers/redis.dart
- neat_cache/pubspec.yaml
We have seen cases with:
> RedisCommandException: OOM command not allowed under OOM prevention
Basically, we're getting an `OOM` error to a get/set command, this can happen if the system runs out of memory. Even if cache-eviction is enabled, memory can be fragmented too much, or other bad thing.
Conclusion was that commands like `get/set` can fail, even when redis is just used as a cache. There is no really good way to handle it. It might be safest to simply close the connection and try again later.
> Reconnect when a redis command fails

- vendor/pubspec.yaml
- vendor/test/pub_test_server.dart
Dart CI Failing due to Tar Package in Vendor.
Upgrade Dart packages: 
tar: ^0.5.1 ->  tar: ^2.0.0
lints: ^2.0.1 -> lints: ^5.0.0
> vendor: Dart CI Failing Fix

- acyclic_steps/CHANGELOG.md
- acyclic_steps/lib/src/fluent_api.dart
- acyclic_steps/pubspec.yaml
Plain and simple moving `package:acyclic_steps` forward, just maintenance.
> Use final class in acyclic_steps

- typed_sql/CHANGELOG.md
- typed_sql/lib/src/adapter/postgres_adapter.dart
- typed_sql/test/typed_sql/crud/blob/blob_test.dart
- typed_sql/test/typed_sql/crud/boolean/boolean_test.dart
- typed_sql/test/typed_sql/crud/datetime/datetime_test.dart
- typed_sql/test/typed_sql/crud/integer/integer_test.dart
- typed_sql/test/typed_sql/crud/real/real_test.dart
- typed_sql/test/typed_sql/crud/text/text_test.dart
- typed_sql/tool/generate_crud_tests.dart
It's not that 'BC' dates are frequently used, or that `DateTime.utc(0)` is important, it's that `DateTime.utc(0)` or `DateTime(0)` can be nice to use instead of `NULL`.
> Support for postgres BC datetimes, notably `DateTime.utc(0)`
